title: 'I am Damola Mabogunje'
author:
  name: 'Damola Mabogunje'
  email: damola@mabogunje.net
taxonomies:
  - category
  - tag
metadata:
  description: 'Software Engineer & Author'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
